edition = "2021"
format_generated_files = false
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hex_literal_case = "Lower"
imports_granularity = "One"
group_imports = "One"
unstable_features = true
use_field_init_shorthand = true
